name: docs

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js 16
                uses: actions/setup-node@v2-beta
                with:
                    node-version: 16

            -   name: Set git identity
                run: |
                    git config --global user.name "Martin Adámek"
                    git config --global user.email "martin@apify.com"

            -   name: Build & deploy docs
                run: |
                    # install project deps
                    npm install --force
                    # go to website dir
                    cd website
                    # install website deps
                    npm install --force
                    # build and deploy the docs
                    npm run deploy
                env:
                    GIT_USER: "B4nan:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}

    squash:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: 'gh-pages'
                    fetch-depth: 0

            -   name: Set git identity
                run: |
                    git config --global user.name "Martin Adámek"
                    git config --global user.email "martin@apify.com"

            -   name: Squash all commits to reduce repository size
                run: |
                    TOTAL_COMMITS="$(($(git rev-list --count HEAD)-1))"
                    echo "squashing $TOTAL_COMMITS commits"
                    git reset HEAD~$TOTAL_COMMITS
                    git add .
                    git commit --amend -m 'crawlee.dev docs'
                    git push --force origin gh-pages
                env:
                    GIT_USER: "B4nan:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
